# Generated by Django 3.1 on 2020-08-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('kf_member', models.IntegerField()),
                ('is_lounge', models.BooleanField(default=False)),
                ('is_shower', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShowerStall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vacant', models.BooleanField(default=True)),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lounge')),
            ],
        ),
    ]
