# Generated by Django 3.1 on 2020-08-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_showerstall_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showerstall',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
    ]
